tap "homebrew/bundle"
tap "homebrew/cask", "https://mirrors.ustc.edu.cn/homebrew-cask.git"
tap "homebrew/core", "https://mirrors.aliyun.com/homebrew/homebrew-core.git"
brew "maven"
brew "nginx"
brew "php"
brew "pkg-config"
brew "tree"
